// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz7zZvbSwhrvx0f8ipbQwL4T2X5oi6rZ8',
    appId: '1:289295335978:web:58d4339ab7e47297fa7953',
    messagingSenderId: '289295335978',
    projectId: 'flutter-arizal',
    authDomain: 'flutter-arizal.firebaseapp.com',
    storageBucket: 'flutter-arizal.firebasestorage.app',
    measurementId: 'G-DQ5H0DHRHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnKwDQr0MYn-EXER4OlNCCLl6mgCIVp34',
    appId: '1:289295335978:android:2f2db6909230a740fa7953',
    messagingSenderId: '289295335978',
    projectId: 'flutter-arizal',
    storageBucket: 'flutter-arizal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ9H7uOsYtgfnSP7g82VXubG8-Ue4u9Mo',
    appId: '1:289295335978:ios:5a54cee051e5e07dfa7953',
    messagingSenderId: '289295335978',
    projectId: 'flutter-arizal',
    storageBucket: 'flutter-arizal.firebasestorage.app',
    androidClientId: '289295335978-etuhepsu1f20n4ljkcf88pdslhc5uqsk.apps.googleusercontent.com',
    iosClientId: '289295335978-t5g4pbk13oge83vn8dajg5mrhpquus2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ9H7uOsYtgfnSP7g82VXubG8-Ue4u9Mo',
    appId: '1:289295335978:ios:5a54cee051e5e07dfa7953',
    messagingSenderId: '289295335978',
    projectId: 'flutter-arizal',
    storageBucket: 'flutter-arizal.firebasestorage.app',
    androidClientId: '289295335978-etuhepsu1f20n4ljkcf88pdslhc5uqsk.apps.googleusercontent.com',
    iosClientId: '289295335978-t5g4pbk13oge83vn8dajg5mrhpquus2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz7zZvbSwhrvx0f8ipbQwL4T2X5oi6rZ8',
    appId: '1:289295335978:web:c3a37e4c37968ebefa7953',
    messagingSenderId: '289295335978',
    projectId: 'flutter-arizal',
    authDomain: 'flutter-arizal.firebaseapp.com',
    storageBucket: 'flutter-arizal.firebasestorage.app',
    measurementId: 'G-C016655M1Y',
  );

}